### ISSUE TITLE
Division durch 0 in einheitsvektor

### ISSUE THREAD

**Issue by thomsmits** [tpe-lecture/group-13#6]
Eine mögliche Division durch 0 in der Methode `einheitsvektor()` wird nicht abgefangen.

**Comment by nfass** [comment]
Innerhalb des Code wurde das nun so gelöst das eine IllegalStateException geworfen ist wenn es sich um ein Nullvektor handelt. Gegenvorschläge oder ist das in Ordnung?

```
        double betrag = this.betrag();
        if (betrag == 0) {
            //Vektor ist ein Nullvektor
            throw new IllegalStateException();
        }
```

**Comment by thomsmits** [comment]
Ist in Ordnung. Die Exceptions sollte aber noch sagen, warum sie geworfen wurde. Also besser

```java
double betrag = this.betrag();
if (betrag == 0) {
    //Vektor ist ein Nullvektor
    throw new IllegalStateException("Betrag des Vektors ist null. " + 
        "Vom Nullvektor existiert kein Einheitsvektor");
}
```

**Comment by nfass** [comment]
Angepasst.
